name: Deploy Hugo site to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
          cache: false  # Disable automatic caching
      
      # Optional: Set up manual caching if desired
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Display Go info
        run: |
          go version
          echo "GOPATH: $GOPATH"
          echo "GOROOT: $GOROOT"
      
      - name: Handle Go dependencies
        run: |
          cat go.mod || echo "go.mod not found"
          cat go.sum || echo "go.sum not found"
          go mod tidy
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Build
        run: |
          hugo mod get
          hugo --minify
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true